function F=eqLongDynamicStickFixed(t,x)
global g myAC delta_e delta_s_0 delta_T_0

V=x(1);
alpha=x(2);
q=x(3);
xEG=x(4);
zEG=x(5);
teta=x(6);
% delta_e viene già definita nel main e passata come variabile globale
delta_s = delta_s_0;
delta_T = delta_T_0;
gamma=teta+myAC.mu_x-alpha;
[~, ~, ~, rho] = atmosisa(-zEG);
mu_rel = (myAC.W/g)/(rho*myAC.S*myAC.b);

% Secondi membri delle (2.6)
F(1) = g*((delta_T*myAC.T/myAC.W)*cos(alpha - myAC.mu_x + myAC.mu_T) ...
       -sin(gamma) ...
       -((rho*V^2)/(2*(myAC.W/myAC.S))) ...
         *(myAC.CD_0 + myAC.K*((myAC.CL_alpha*alpha ...
            + myAC.CL_delta_e*delta_e(t) ...
            + myAC.CL_delta_s*delta_s)^myAC.m)));

F(2) = (1/(1+((myAC.mac/myAC.b)*myAC.CL_alpha_dot)/(4*mu_rel)))*( 1. - myAC.CL_q*(myAC.mac/myAC.b)/(4*mu_rel) )*q ...
       -(g/V)*(delta_T*myAC.T/myAC.W)*sin(alpha - myAC.mu_x + myAC.mu_T) ...
       +(g/V)*cos(gamma) ...
       -((rho*V*g)/(2*(myAC.W/myAC.S))) ...
         *( myAC.CL_alpha*alpha + myAC.CL_delta_e*delta_e(t) ...
            + myAC.CL_delta_s*delta_s);
          
F(3) = ((V^2)*(myAC.mac/myAC.b)/((myAC.k_y^2)*2*mu_rel))*(myAC.Cm_0 + myAC.Cm_alpha*alpha ...
        + myAC.Cm_delta_s*delta_s ...
        + myAC.Cm_delta_e*delta_e(t) ...
        + (myAC.mac/(2*V))*myAC.Cm_q*q ...
        + myAC.Cm_T_0 + myAC.Cm_T_alpha*alpha+(myAC.mac/(2*V))*myAC.Cm_alpha_dot*F(2));
F(4)=V*cos(gamma);
F(5)=-V*sin(gamma);
F(6)=q;
F=F';
end